# -*- coding: utf-8 -*-
"""APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19TSzNb0CPgdNRKReGTp0p5YblutPXFFx
"""


import warnings
warnings.filterwarnings(
    "ignore",
    message="The 'css' parameter in the Blocks constructor will be removed in Gradio 6.0.*",
    category=DeprecationWarning,
)

import gradio as gr
import requests
import pandas as pd
import urllib.parse
import re
import os
import glob
import shutil
import time
import zipfile
from datetime import datetime

from rdkit import Chem
from rdkit.Chem import Descriptors, Lipinski

BASE = "https://cb.imsc.res.in/imppat"
HEADERS = {"User-Agent": "Mozilla/5.0"}
OUTPUT_DIR = "outputs"

custom_css = """
@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;600&display=swap');

.gradio-container {
    font-family: 'IBM Plex Sans', sans-serif !important;
    background: #ffffff !important;
}

button {
    background: #FEFFFE !important;
    border: 1px solid #F1F6EF !important;
    color: #2E4A2E !important;
    font-weight: 600 !important;
    box-shadow: 0 4px 14px rgba(60, 90, 60, 0.12) !important;
}

button:hover {
    background: #FBFDFB !important;
    box-shadow: 0 6px 18px rgba(60, 90, 60, 0.16) !important;
}

.step-chip {
    display: inline-block;
    padding: 10px 14px;
    margin-top: 14px;
    margin-bottom: 10px;
    border-radius: 4px;
    border: 1px solid #B9DEB3;
    background: #F8FDF5;
    color: #3E6B3E;
    font-weight: 700;
    box-shadow: 0 1px 3px rgba(70, 120, 70, 0.04);
}

footer {
    background: #ffffff !important;
    border: none !important;
}

footer button,
footer a {
    background: #ffffff !important;
    color: #444 !important;
    border: none !important;
    box-shadow: none !important;
}

footer button:hover,
footer a:hover {
    background: #ffffff !important;
    color: #111 !important;
    border: none !important;
    box-shadow: none !important;
}
"""

def ensure_output_dir():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    return OUTPUT_DIR


def timestamp_tag():
    return datetime.now().strftime("%Y%m%d_%H%M%S")


def resolve_uploaded_path(file_value):
    if not file_value:
        return None
    if isinstance(file_value, str):
        return file_value
    if isinstance(file_value, dict):
        return file_value.get("path") or file_value.get("name")
    file_name = getattr(file_value, "name", None)
    return file_name


def fetch_page(plant):
    url = f"{BASE}/phytochemical/{urllib.parse.quote(plant)}"
    r = requests.get(url, timeout=25, headers=HEADERS)
    r.raise_for_status()
    return r.text


def fetch_detail_page(imphy_id):
    url = f"{BASE}/phytochemical-detailedpage/{imphy_id}"
    r = requests.get(url, timeout=25, headers=HEADERS)
    r.raise_for_status()
    return r.text


def extract_entries(html):
    entries = []

    try:
        tables = pd.read_html(html)
        for table in tables:
            cols = [str(c).strip() for c in table.columns]
            if "IMPPAT Phytochemical identifier" in cols and "Phytochemical name" in cols:
                sub = table[["IMPPAT Phytochemical identifier", "Phytochemical name"]].copy()
                sub.columns = ["IMPHY_ID", "Phytochemical_Name"]

                for _, row in sub.iterrows():
                    imphy_id = str(row["IMPHY_ID"]).strip()
                    name = str(row["Phytochemical_Name"]).strip()
                    if re.fullmatch(r"IMPHY\d+", imphy_id):
                        entries.append({
                            "IMPHY_ID": imphy_id,
                            "Phytochemical_Name": name
                        })
                break
    except Exception:
        pass

    if entries:
        seen = set()
        deduped = []
        for item in entries:
            if item["IMPHY_ID"] not in seen:
                seen.add(item["IMPHY_ID"])
                deduped.append(item)
        return deduped

    pairs = re.findall(r"(IMPHY\d+)\s*</td>\s*<td[^>]*>\s*([^<]+)", html, flags=re.IGNORECASE)
    seen = set()
    for imphy_id, name in pairs:
        if imphy_id not in seen:
            seen.add(imphy_id)
            entries.append({
                "IMPHY_ID": imphy_id.strip(),
                "Phytochemical_Name": name.strip()
            })

    return entries


def extract_smiles(detail_html):
    text = re.sub(r"<[^>]+>", " ", detail_html)
    text = re.sub(r"\s+", " ", text).strip()

    patterns = [
        r"SMILES:\s*(.*?)\s*InChI:",
        r"SMILES:\s*(.*?)\s*InChIKey:",
        r"SMILES:\s*(.*?)\s*Functional groups:",
    ]

    for pattern in patterns:
        m = re.search(pattern, text, flags=re.IGNORECASE)
        if m:
            return m.group(1).strip()

    return ""


def ro5_from_smiles(smiles):
    if not smiles:
        return "No SMILES"

    try:
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return "Invalid SMILES"

        mw = Descriptors.MolWt(mol)
        logp = Descriptors.MolLogP(mol)
        hbd = Lipinski.NumHDonors(mol)
        hba = Lipinski.NumHAcceptors(mol)

        violations = 0
        if mw > 500:
            violations += 1
        if logp > 5:
            violations += 1
        if hbd > 5:
            violations += 1
        if hba > 10:
            violations += 1

        if violations <= 1:
         return "Passed"
        suffix = "violations"
        return f"Failed ({violations} {suffix})"
    except Exception:
        return "RDKit Error"


def style_ro5(df):
    def row_style(row):
        ro5 = str(row.get("RO5_Status", ""))
        if ro5.startswith("Failed"):
            return ["background-color: #fff8f8; color: #7a3b3b;"] * len(row)
        return [""] * len(row)

    return df.style.apply(row_style, axis=1)


def run(plant):
    plant_name = str(plant or "").strip()
    if not plant_name:
        return None, None, None, "Please enter a plant name."

    try:
        html = fetch_page(plant_name)
    except requests.RequestException as exc:
        return None, None, None, f"Failed to fetch phytochemical page: {exc}"

    entries = extract_entries(html)

    if not entries:
        return None, None, None, "No phytochemicals found."

    rows = []
    for item in entries:
        imphy_id = item["IMPHY_ID"]
        name = item["Phytochemical_Name"]

        try:
            detail_html = fetch_detail_page(imphy_id)
            smiles = extract_smiles(detail_html)
        except Exception:
            smiles = ""

        ro5_status = ro5_from_smiles(smiles)

        rows.append({
            "IMPHY_ID": imphy_id,
            "Phytochemical_Name": name,
            "SMILES": smiles,
            "RO5_Status": ro5_status
        })

    df = pd.DataFrame(rows)
    display_df = df.copy()

    safe_name = re.sub(r"[^A-Za-z0-9_]+", "_", plant_name).strip("_") or "plant"
    out_dir = ensure_output_dir()
    file = os.path.join(out_dir, f"{safe_name}_phytochemicals_{timestamp_tag()}.csv")
    df.to_csv(file, index=False)

    total_count = len(df)
    passed_count = (df["RO5_Status"] == "Passed").sum()

    msg = (
        f"Total : {total_count} phytochemicals\n"
        f"RO5 passed: {passed_count}"
    )

    return display_df, file, file, msg


def download_sdf(imphy_id, folder):
    imphy_id = str(imphy_id).strip()
    url = f"{BASE}/images/3D/SDF/{imphy_id}_3D.sdf"
    max_attempts = 3
    for attempt in range(max_attempts):
        try:
            r = requests.get(url, timeout=25, headers=HEADERS)
            if r.status_code == 200 and len(r.text.strip()) > 50:
                path = os.path.join(folder, f"{imphy_id}.sdf")
                with open(path, "w", encoding="utf-8") as f:
                    f.write(r.text)
                return path
        except Exception:
            pass

        if attempt < max_attempts - 1:
            time.sleep(1 + attempt)
        pass

    return None


def make_imppat_link(imphy_id):
    return f"{BASE}/phytochemical-detailedpage/{imphy_id}"


def find_cached_sdf(imphy_id, output_dir):
    pattern = os.path.join(output_dir, "sdf_files_*", f"{imphy_id}.sdf")
    candidates = glob.glob(pattern)
    if not candidates:
        return None

    valid = [p for p in candidates if os.path.isfile(p) and os.path.getsize(p) > 50]
    if not valid:
        return None

    return max(valid, key=os.path.getmtime)


def use_cached_sdf(imphy_id, folder, output_dir):
    cached = find_cached_sdf(imphy_id, output_dir)
    if not cached:
        return None

    dest = os.path.join(folder, f"{imphy_id}.sdf")
    try:
        shutil.copy2(cached, dest)
        return dest
    except Exception:
        return None


def run_sdf_from_previous(csv_file, sdf_mode):
    csv_path = resolve_uploaded_path(csv_file)
    if not csv_path:
        return "Please run Step 1 first.", None, None
    if not os.path.exists(csv_path):
        return "Selected CSV file was not found.", None, None

    try:
        df = pd.read_csv(csv_path, dtype=str)
    except Exception as exc:
        return f"Could not read CSV file: {exc}", None, None

    if "IMPHY_ID" not in df.columns:
        return "CSV must contain IMPHY_ID column", None, None

    work_df = df.copy()

    if sdf_mode == "Lipinski Passed Only":
        if "RO5_Status" not in work_df.columns:
            return "CSV must contain RO5_Status column for Lipinski filtering.", None, None
        work_df = work_df[work_df["RO5_Status"].fillna("").str.strip() == "Passed"]

    out_dir = ensure_output_dir()
    folder = os.path.join(out_dir, f"sdf_files_{timestamp_tag()}")
    os.makedirs(folder, exist_ok=True)

    saved = []
    missing = []

    ids = work_df["IMPHY_ID"].dropna().astype(str).str.strip().tolist()
    ids = [x for x in ids if x]

    for imphy in ids:
        if re.fullmatch(r"IMPHY\d+", imphy):
            path = use_cached_sdf(imphy, folder, out_dir)
            if not path:
                path = download_sdf(imphy, folder)
            if path:
                saved.append(path)
            else:
                missing.append(imphy)
        else:
            missing.append(imphy)

    zip_name = None
    if saved:
        zip_name = os.path.join(out_dir, f"IMPPAT_3D_SDF_{timestamp_tag()}.zip")
        with zipfile.ZipFile(zip_name, "w") as z:
            for f in saved:
                z.write(f, arcname=os.path.basename(f))

    missing_file = None
    if missing:
        missing_df = pd.DataFrame({"Missing_IMPHY_ID": missing})
        missing_file = os.path.join(out_dir, f"missing_imphy_ids_{timestamp_tag()}.csv")
        missing_df.to_csv(missing_file, index=False)

    if missing:
        missing_links = ", ".join(
            f"[{imphy}]({make_imppat_link(imphy)})" for imphy in missing
        )
    else:
        missing_links = "None"

    msg = (
        f"**Download Mode:** {sdf_mode}\n\n"
        f"**Total IDs selected:** {len(ids)}\n\n"
        f"**Downloaded SDF files:** {len(saved)}\n\n"
        f"**Missing / not available:** {len(missing)}\n\n"
        f"**Missing IDs:** {missing_links}"
    )

    return msg, zip_name, missing_file


with gr.Blocks(title="IMPPATez") as demo:
    gr.HTML("""
    <div style="width:100%; max-width:980px; margin: 10px auto 20px auto; text-align:center;">

    <!-- Centered Logo -->
    <div style="display:flex; justify-content:center; align-items:center; margin-bottom:12px;">
        <img src="https://i.ibb.co.com/Q38pzfNc/1776435449657.png"
             style="height:130px; width:auto;" />
    </div>

    <div style="margin-top:6px; font-weight:600;">
        🔎 IMPHY ID Extractor | 📦 Automated 3D SDF Downloader | ☁️ Cloud Ready
    </div>

    <div style="margin-top:6px; color:#666; font-size:0.9rem;">
        🧬 Natural Product Informatics Tool | ⚡ IMPPAT Database Automation
    </div>

    </div>
    """)

    stored_csv = gr.State()

    gr.HTML('<div class="step-chip">1. Search Plant and Show IMPHY ID, Name, SMILES, RO5</div>')

    with gr.Row():
        plant = gr.Textbox(label="Plant Name", placeholder="Enter plant name", scale=8)
        btn1 = gr.Button("🔍", scale=1)

    step1_status = gr.Textbox(label="Search Status", lines=2)
    preview = gr.Dataframe(label="Phytochemical Results", interactive=False)
    out1 = gr.File(label="Generated CSV")

    btn1.click(
        run,
        inputs=plant,
        outputs=[preview, out1, stored_csv, step1_status]
    )

    gr.HTML('<div class="step-chip">2. 3D SDF Downloader</div>')

    sdf_mode = gr.Radio(
        choices=["Lipinski Passed Only", "Lipinski Passed + Failed"],
        value="Lipinski Passed + Failed",
        label="SDF Download Mode"
    )

    btn2 = gr.Button("Download 3D SDF ZIP From Generated CSV")
    status = gr.Markdown(label="Status")
    out2 = gr.File(label="Download ZIP")
    out3 = gr.File(label="Missing IDs Report")

    btn2.click(run_sdf_from_previous, inputs=[stored_csv, sdf_mode], outputs=[status, out2, out3])

    gr.HTML("""
    <div style="width:100%; max-width:980px; margin: 20px auto; text-align:center; color:#666; font-size:0.85rem;">
        IMPPATez · Python · Gradio · Requests · Pandas · RDKit<br>
        Automated phytochemical extraction, RO5 check & 3D molecular structure retrieval<br>
        <b>Nabiul Orko | Planteran 🍀 <b>
    </div>
    """)

if __name__ == "__main__":
    demo.launch(share=True, debug=False, css=custom_css)
